### ISSUE TITLE
CSS issues after running

### ISSUE THREAD

**Issue by tjolson** [tillahoffmann/obsidian-jupyter#10]
**Describe the bug**
After running the code snippet I'm getting issues with the styling of the output and Obsidian overall. 

**Screenshots**
<img width="1280" alt="Screen Shot 2021-09-07 at 21 48 34" src="https://user-images.githubusercontent.com/66096592/132402457-9a5f2dc6-b722-45e8-b26b-6b48b557e77e.png">

**Comment by tillahoffmann** [comment]
Three follow up questions:

* Could you run the tests from the plugin settings and share the console logs beginning with `Received response [some html code]`?
* Could you run `pip freeze` from the command line and paste the output here?
* Could you run `curl -L https://bit.ly/3jTncQw | jupyter nbconvert --execute --stdin --stdout --to html --template basic` from the command line and paste the output here?

**Comment by Gareth-Wong** [comment]
Sorry to hijack this thread, but I am also having the same error message showing.

Here are some screenshots of 1. before running the cell, 2. after clicking run once, and then 3. clicking run a second time. 


![Screen Shot 2021-09-10 at 10 49 49 AM](https://user-images.githubusercontent.com/37307109/132873230-6b481838-3304-4ff7-83b0-2a157aa276eb.png)
![Screen Shot 2021-09-10 at 10 50 00 AM](https://user-images.githubusercontent.com/37307109/132873232-d8bea9e7-faa2-41d8-b539-ba5905573166.png)
![Screen Shot 2021-09-10 at 10 50 08 AM](https://user-images.githubusercontent.com/37307109/132873233-ffd28571-78ee-4b0b-b5b9-21ad4ccd8158.png)

**Comment by tillahoffmann** [comment]
* Could you run the tests from the plugin settings and share the console logs beginning with `Received response [some html code]`?
* Could you run `pip freeze` from the command line and paste the output here?
* Could you run `curl -L https://bit.ly/3jTncQw | jupyter nbconvert --execute --stdin --stdout --to html --template basic` from the command line and paste the output here?

**Comment by Gareth-Wong** [comment]
1. https://gist.github.com/Gareth-Wong/0983b9c1773dea71671abecd1a3f2836
2. https://gist.github.com/Gareth-Wong/8705626a8b35e69fa49b6a630ddfd7d9
3. https://gist.github.com/Gareth-Wong/1d686549a22f16834cafc0be86c12118

**Comment by tillahoffmann** [comment]
It looks like your python dependencies are outdates. Could you update to at least the versions shown [here](https://github.com/tillahoffmann/obsidian-jupyter#installation) and try again?
