### ISSUE TITLE
Jupyter plugin not available in the plugin options list

### ISSUE THREAD

**Issue by aTrotier** [tillahoffmann/obsidian-jupyter#11]
# Description
Jupyter plugin is not showing in the plugin options list
I also tried it in a fresh new vault same

# Specification
- MacOs

# Screenshots
![image](https://user-images.githubusercontent.com/12255163/132842073-fa98a0c0-ead0-478d-891f-3e308ff41711.png)

**Comment by tillahoffmann** [comment]
Two follow up questions:

- did you install Obsidian via the app store or downloaded it from the website?
- could you share the output from the developer console?

**Comment by aTrotier** [comment]
Thanks, I didnot know that the developer console exists.
![image](https://user-images.githubusercontent.com/12255163/132852077-671b7729-3411-4a7d-9ee9-7518b36b0b80.png)

It was an issue with my enterprise proxy. I tried on another networks and it worked :)
