### ISSUE TITLE
sys.stdout.reconfigure(line_buffering=True) AttributeError: '_io.TextIOWrapper' object has no attribute 'reconfigure'

### ISSUE THREAD

**Issue by Jacobxz** [tillahoffmann/obsidian-jupyter#12]
sys.stdout.reconfigure(line_buffering=True)
AttributeError: '_io.TextIOWrapper' object has no attribute 'reconfigure'
![image](https://user-images.githubusercontent.com/48195963/132850007-7d29e614-800b-47da-b77e-2a639de549d0.png)

**Comment by tillahoffmann** [comment]
This should work once you update your python version to `>=3.7`. Feel free to follow up if not.

**Comment by Jacobxz** [comment]
> This should work once you update your python version to `>=3.7`. Feel free to follow up if not.

Is there any solution for the lower version?

**Comment by tillahoffmann** [comment]
Modifying the code to work around the [offending line](https://github.com/tillahoffmann/obsidian-jupyter/blob/master/obsidian-jupyter.py#L29) is an option, but python 3.6 is relatively old and won't receive security patches beyond the end of the year. PRs welcome though.

**Comment by Jacobxz** [comment]
> Modifying the code to work around the [offending line](https://github.com/tillahoffmann/obsidian-jupyter/blob/master/obsidian-jupyter.py#L29) is an option, but python 3.6 is relatively old and won't receive security patches beyond the end of the year. PRs welcome though.
 
Thank you very much, 3.7 is running normally😁
