### ISSUE TITLE
Request: Hotkey to run code? 

### ISSUE THREAD

**Issue by Keysz** [tillahoffmann/obsidian-jupyter#16]
Fantastic plugin. Is there a way to run the cell without having to click the 'Run" bottom on the top right? If not, would it be possible to incorporate one?

**Comment by tillahoffmann** [comment]
That sounds like a good idea. Unfortunately, I'm not sure as to the best implementation. Any suggestions welcome!

The current code acts as a [markdown code block processor](https://github.com/tillahoffmann/obsidian-jupyter/blob/a981646013ebbcac9482ac561ded8d5b89cde853/main.ts#L87-L117) which adds a button that [executes the code when the user clicks it](https://github.com/tillahoffmann/obsidian-jupyter/blob/a981646013ebbcac9482ac561ded8d5b89cde853/main.ts#L100-L116). I don't know how I would be able to obtain the arguments of the post processor function from a keyboard shortcut. But it's likely possible for someone with more Obsidian plugin development experience.

**Comment by ndahn** [comment]
From what I found: adding a new command is straight forward [according to the docs](https://marcus.se.net/obsidian-plugin-docs/user-interface/commands). To get the current block requires some trickery, but using an [editorCheckCallback](https://marcus.se.net/obsidian-plugin-docs/reference/typescript/interfaces/Command#editorcheckcallback) you can get a reference to the editor, then the current line and from that the [current code block](https://github.com/artem-barmin/obsidian-block-drag-n-drop/blob/ca23f7d74b7966ebcb0a3248f5e97dae71428734/main.ts#L147). It's also possible to [iterate over all code blocks](https://github.com/jdbrice/obsidian-code-block-copy/blob/9b0760bd912496e1056fffe651efbea48a53c797/main.ts#L29) using a query and running the processor on all of them.
