### ISSUE TITLE
ipywidgets not appearing

### ISSUE THREAD

**Issue by slamijami** [tillahoffmann/obsidian-jupyter#20]
I am trying to get simple widgets to appear but all I get is a <function __main__.say_my_name(name)> output.

![image](https://user-images.githubusercontent.com/91186645/138011272-87ab2fef-c9d6-401c-a15e-f82d726f9fd0.png)

plugin 'run test' output:
![image](https://user-images.githubusercontent.com/91186645/138012867-909913cc-a42c-40c7-baae-68c3226ebb93.png)

'pip freeze' output:

anyio==3.3.1
argon2-cffi==21.1.0
astropy==4.3.1
astroquery==0.4.3
attrs==21.2.0
Babel==2.9.1
backcall==0.2.0
beautifulsoup4==4.9.3
bleach==4.1.0
certifi==2021.5.30
cffi==1.15.0
charset-normalizer==2.0.4
colorama==0.4.4
cycler==0.10.0
debugpy==1.5.1
decorator==5.1.0
defusedxml==0.7.1
entrypoints==0.3
html5lib==1.1
idna==3.2
importlib-metadata==4.8.1
ipykernel==6.4.2
ipympl==0.7.0
ipython==7.28.0
ipython-genutils==0.2.0
ipywidgets==7.6.5
jedi==0.18.0
Jinja2==3.0.2
jplephem==2.16
json5==0.9.6
jsonschema==4.1.1
jupyter==1.0.0
jupyter-client==7.0.6
jupyter-console==6.4.0
jupyter-contrib-core==0.3.3
jupyter-contrib-nbextensions==0.5.1
jupyter-core==4.8.1
jupyter-highlight-selected-word==0.2.0
jupyter-js-widgets-nbextension==0.0.2.dev0
jupyter-latex-envs==1.4.6
jupyter-nbextensions-configurator==0.4.1
jupyter-server==1.11.0
jupyterlab==3.1.12
jupyterlab-pygments==0.1.2
jupyterlab-server==2.8.1
jupyterlab-widgets==1.0.2
keyring==23.1.0
kiwisolver==1.3.2
llvmlite==0.37.0
lxml==4.6.3
MarkupSafe==2.0.1
matplotlib==3.4.3
matplotlib-inline==0.1.3
mimeparse==0.1.3
mistune==0.8.4
nbclassic==0.3.2
nbclient==0.5.4
nbconvert==6.2.0
nbextension-cellfolding==0.0.3
nbformat==5.1.3
nest-asyncio==1.5.1
notebook==6.4.5
numba==0.54.0
numpy==1.20.0
packaging==21.0
pandas==1.3.2
pandocfilters==1.5.0
parso==0.8.2
pickleshare==0.7.5
Pillow==8.3.2
plotly==5.3.1
poliastro==0.15.2
prometheus-client==0.11.0
prompt-toolkit==3.0.20
pycparser==2.20
pyerfa==2.0.0
Pygments==2.10.0
pyparsing==2.4.7
pyrsistent==0.18.0
python-dateutil==2.8.2
pytz==2021.1
pyvo==1.1
pywin32==302
pywin32-ctypes==0.2.0
pywinpty==1.1.4
PyYAML==5.4.1
pyzmq==22.3.0
qtconsole==5.1.1
QtPy==1.11.2
renderjs-nbextension==0.0.5
requests==2.26.0
requests-unixsocket==0.2.0
scipy==1.7.1
Send2Trash==1.8.0
six==1.16.0
sniffio==1.2.0
soupsieve==2.2.1
tenacity==8.0.1
terminado==0.12.1
testpath==0.5.0
tornado==6.1
traitlets==5.1.0
urllib3==1.26.6
wcwidth==0.2.5
webencodings==0.5.1
websocket-client==1.2.1
widgetsnbextension==3.5.1
zipp==3.5.0
Note: you may need to restart the kernel to use updated packages.

**Comment by tillahoffmann** [comment]
Hey, this plugin is designed as a rudimentary tool to facilitate inline evaluation of code within obsidian. It will not achieve feature parity with jupyter, e.g. include widgets and advanced functionality (such as tqdm progress bars). However, contributions are welcome.
