### ISSUE TITLE
Run in edit mode

### ISSUE THREAD

**Issue by Mixpap** [tillahoffmann/obsidian-jupyter#21]
This plugin is amazing and maybe can change the way many people work using jupyter. Is there a way that the code can run in edit mode and append the results there, as the obsidian-calc plugin works?
 
https://github.com/meld-cp/obsidian-calc

Thanks a lot!

**Comment by kkharji** [comment]
Also a shortcut might great so I can run the current codeblock

**Comment by tillahoffmann** [comment]
> Also a shortcut might great so I can run the current codeblock

Let's track that one in #21.

**Comment by tillahoffmann** [comment]
> Also a shortcut might great so I can run the current codeblock

Let's track that one in #16.
