### ISSUE TITLE
Display latex correctly 

### ISSUE THREAD

**Issue by mister-choo** [tillahoffmann/obsidian-jupyter#22]
Right now this code:
```jupyter
import sympy

sympy.sqrt(3)
```
Results in a `$\displaystyle \sqrt{3}$` string appearing. Considering obsidian mathjax support it should be possible to display it as latex instead?

**Comment by tillahoffmann** [comment]
That sounds like an interesting idea but is out of scope for the purpose of this project (providing a basic interface to run code). It would require post-processing the results, and it is not immediately obvious which results should be post-processed and which should not. Contributions are however welcome.
