### ISSUE TITLE
The results should be available in the note after close it?

### ISSUE THREAD

**Issue by igorpereirabr1** [tillahoffmann/obsidian-jupyter#23]
**Before raising an issue**
Have you installed all required dependencies? 
Yes

**Describe the bug**
After close the Note, the results disappear, can we do something to keep re results available without executing the code again?

**Comment by tillahoffmann** [comment]
I'm afraid that would require an additional database to store the results because Obsidian is markdown based and cannot easily store arbitrary information without messing up the editor. Contributions are welcome, but I consider this out of scope for a basic plugin to run code.

**Comment by Hxppdv** [comment]
Actually, something similar is implemented in the [Desmos plugin](https://github.com/Nigecat/obsidian-desmos), they use some kind of local image cache to achieve this effect, which would be a great feature, and it would be nice if someone could implement it.
