### ISSUE TITLE
AttributeError: module 'jinja2.utils' has no attribute 'escape'

### ISSUE THREAD

**Issue by aidan-gibson** [tillahoffmann/obsidian-jupyter#38]
This is an issue with nbconvert
https://github.com/jupyter/nbconvert/issues/1736

**Comment by dclimber** [comment]
@aidan-gibson here's my workaround:
1. Installed recommended package versions:

```
jupyter==1.0.0
jupyter-client==7.0.2
jupyter-console==6.4.0
jupyter-core==4.7.1
jupyterlab-pygments==0.1.2
jupyterlab-widgets==1.0.1
nbclient==0.5.4
nbconvert==6.1.0
nbformat==5.1.3
notebook=6.4.3
```

2. Activated virtual environment into which I installed them.
3. `pip uninstall jinja2`
4. `pip install jinja2==3.0.3`

Works now.

**Comment by aidan-gibson** [comment]
Thank you!

**Comment by aidan-gibson** [comment]
I'll just leave this open for now until nbconvert fixes the issue, so others can see.
