### ISSUE TITLE
Glitchy in Obsidian Live Preview

### ISSUE THREAD

**Issue by aidan-gibson** [tillahoffmann/obsidian-jupyter#39]
In Obsidian Reader View, everything runs as expected (shown in screencap below).

![iframe-reading](https://user-images.githubusercontent.com/20917687/160257805-99389f9d-a871-4375-8bd6-107c2a6a1e5c.png)

In Obsidian Live Preview view, three backticks are visible after the print statement; they should not be there. The formatting of the output cell is also significantly messier, taking up much more space than it should and not having a distinct separation from the source code cell.
![iframe-livepreview](https://user-images.githubusercontent.com/20917687/160257837-89510c44-f6f3-47ef-af65-55ebfd567908.png)

Expected Behavior: Everything in Live Preview mode should mirror Reading mode exactly; except when the code block is being edited.

(P.S. THANK YOU for making this plugin! I'm absolutely in love with this and will try to submit PRs when possible. I'm extremely excited for other languages being supported as well.)

**Comment by Loigzorn** [comment]
yes I can confirm the behaviour, its the same for me

![image](https://user-images.githubusercontent.com/43932432/167684364-f9e78bf0-40ca-43dd-b40a-aab4e5bdf530.png)

**Comment by Loigzorn** [comment]
@tillahoffmann as you pinned the issue as 'help wanted', do you have a clue what the steps required to resolve this bug? Or do you have a clue what might cause this behaviour?

**Comment by tillahoffmann** [comment]
It would require someone to have a look at the CSS/HTML that's used in the live preview mode and determine how/why the output of the Jupyter cell interferes with it. Another option would be to wrap the result in an `iframe` as in #40, but the size of the frame would have to be adjusted at runtime to fit the content. The `help wanted` label encourages contributions in the form of PRs.
