### ISSUE TITLE
No run button

### ISSUE THREAD

**Issue by ghost** [tillahoffmann/obsidian-jupyter#4]
- python 3.9.6 installed
- console:
loading jupyter plugin
Faiiled to load resource: net::ERR_CONNECTION_REFUSED 127.0.0.1:8765/:1 ( <-- is this related? )
- Preview: **no run button**
- But: Your example code runs successfully in visual studio code.

**Comment by tillahoffmann** [comment]
Not sure whether `Faiiled to load resource: net::ERR_CONNECTION_REFUSED 127.0.0.1:8765/:1` is related. Do you have a screenshot of the code and preview side by side?

**Comment by ghost** [comment]
***@***.*** "Screen Shot 2021-09-04 at 16.57.13.jpg")

<pre>
```
               _\|/_
               (o o)
+-----------oOO-{_}-OOo-----------+
|         __ _     _ _            |
|   __ _ / _(_) __| (_) __ _ ___  |
|  / _` | |_| |/ _` | |/ _` / __| |
| | (_| |  _| | (_| | | (_| \__ \ |
|  \__, |_| |_|\__,_|_|\__,_|___/ |
|  |___/                          |
+---------------------------------+
  George Fidias - Grevena, Greece  ```
</pre>

On 4 Sep 2021, at 15:51, Till Hoffmann wrote:

> Not sure whether `Faiiled to load resource: net::ERR_CONNECTION_REFUSED 127.0.0.1:8765/:1` is related. Do you have a screenshot of the code and preview side by side?
>
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/tillahoffmann/obsidian-jupyter/issues/4#issuecomment-912969389

**Comment by tillahoffmann** [comment]
I’m afraid GitHub doesn’t process attachments when sent by email.

**Comment by ghost** [comment]
![scrnshot](https://user-images.githubusercontent.com/23036873/132097992-ee883c6f-3c06-4e08-93b0-162006dd7987.jpg)

**Comment by ghost** [comment]
Created new empty vault.
Installed obsidian-jupyter plugin.
Copied the same file (as shown above).
Run button shows (seems there's a conflict with one of my other installed plugins)-
But when I press it I get this:
/usr/local/bin/python3: can't open file '/Users/gfidias/Documents/test_vault/.obsidian/plugins/obsidian-jupyter/**obsidian-jupyter.py': [Errno 2] No such file or directory**

**Comment by ghost** [comment]
Copied obsidian-jupyter.py from your site in the plugin's dir.
Now I get this:

```
{filename: "jupyter.md", filepath: "Inbox/jupyter.md", vault: "test_vault", workspace: ""}

main.ts:135 created new client for doc 8335c93d387694c7
[Violation] 'click' handler took 1839ms
main.ts:43 INFO:obsidian-jupyter:started server for document 8335c93d387694c7

main.ts:43 INFO:obsidian-jupyter:received request: {"id":"f6ed66b0-ef76-4456-a417-be6f08400a0d","body":{"command":"execute","source":"import numpy as np\nfrom matplotlib import pyplot as plt\n\nx = np.linspace(0, 1)\ny = np.exp(-x) * np.sin(4 * np.pi * x)\nplt.plot(x, y)\npass\n"}}


main.ts:43 INFO:traitlets:Executing notebook with kernel: 

main.ts:43 Traceback (most recent call last):
  File "/Users/gfidias/Library/Python/3.9/lib/python/site-packages/traitlets/traitlets.py", line 535, in get

main.ts:43     value = obj._trait_values[self.name]
KeyError: 'template_paths'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gfidias/Documents/personal/test_vault/.obsidian/plugins/obsidian-jupyter/obsidian-jupyter.py", line 48, in <module>

main.ts:43     html_exporter = HTMLExporter(template_name='basic')
  File "/usr/local/lib/python3.9/site-packages/nbconvert/exporters/templateexporter.py", line 330, in __init__

main.ts:43     super().__init__(config=config, **kw)
  File "/usr/local/lib/python3.9/site-packages/nbconvert/exporters/exporter.py", line 114, in __init__

main.ts:43     self._init_preprocessors()
  File "/usr/local/lib/python3.9/site-packages/nbconvert/exporters/templateexporter.py", line 497, in _init_preprocessors

main.ts:43     conf = self._get_conf()
  File "/usr/local/lib/python3.9/site-packages/nbconvert/exporters/templateexporter.py", line 515, in _get_conf

main.ts:43     for path in map(Path, self.template_paths):
  File "/Users/gfidias/Library/Python/3.9/lib/python/site-packages/traitlets/traitlets.py", line 575, in __get__

main.ts:43     return self.get(obj, cls)
  File "/Users/gfidias/Library/Python/3.9/lib/python/site-packages/traitlets/traitlets.py", line 538, in get

main.ts:43     default = obj.trait_defaults(self.name)
  File "/Users/gfidias/Library/Python/3.9/lib/python/site-packages/traitlets/traitlets.py", line 1578, in trait_defaults

main.ts:43     return self._get_trait_default_generator(names[0])(self)
  File "/Users/gfidias/Library/Python/3.9/lib/python/site-packages/traitlets/traitlets.py", line 975, in __call__

main.ts:43     return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/nbconvert/exporters/templateexporter.py", line 526, in _template_paths

main.ts:43     template_names = self.get_template_names()
  File "/usr/local/lib/python3.9/site-packages/nbconvert/exporters/templateexporter.py", line 609, in get_template_names

main.ts:43     raise ValueError('No template sub-directory with name %r found in the following paths:\n\t%s' % (base_template, paths))
ValueError: No template sub-directory with name 'basic' found in the following paths:
	/Users/gfidias/Library/Jupyter
	/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/share/jupyter
	/usr/local/share/jupyter
	/usr/share/jupyter
```

**Comment by tillahoffmann** [comment]
Good point, the `obsidian-jupyter.py` file was missing from the release (now added).

Regarding the missing button, my guess would be that it doesn't appear because of an interaction with the theme you're using. Which theme is it? Or did it work in the new vault with the same theme?

Regarding the error message in the console, there seems to be an issue with your `nbconvert` installation. These two links might be helpful in resolving things:

* https://github.com/jupyter/nbconvert/issues/1369
* https://stackoverflow.com/q/63958574/1150961

**Comment by ghost** [comment]
Using the pisum theme.
Tried other themes and no theme - not working.
Repaired nbconvert installation: Now everything is working in my test_vault but still no run button in my main vault.

**Comment by tillahoffmann** [comment]
Interesting, can you see whether the HTML element for the button exists in the DOM but is not showing up due to problems in the CSS or whether the element just doesn't get added to the DOM?

**Comment by ghost** [comment]
Checked console messages >
Found conflict with the obsidian-banners plugin (https://github.com/noatpad/obsidian-banners) >
Disabled it > it's working.

![scrnshot](https://user-images.githubusercontent.com/23036873/132108409-40314d59-9242-4dca-958d-c3fe6b2cec3d.jpg)

**Comment by ghost** [comment]
I don't know why but after the latest updates (obsidian app and plugins) the banner plugin no longer conflicts with the jupyter plugin. They work happily together.
Thought I should let you know.

**Comment by j-koreth** [comment]
Sweet. Just to let you all know the Readme mentions that they conflict.
