### ISSUE TITLE
The Chinese characters in the string are not supported

### ISSUE THREAD

**Issue by luzhengang-phy** [tillahoffmann/obsidian-jupyter#43]

**Comment by tillahoffmann** [comment]
Could you please provide further details as outlined in the issue template?

**Comment by luzhengang-phy** [comment]
![issue](https://user-images.githubusercontent.com/76544541/172396209-4547507c-f79a-4bd5-baec-621d30ec838d.png)

**Comment by luzhengang-phy** [comment]
When I used jupyter blocks in Obsidian, I couldn't print Chinese characters when printing strings, but I had no problem using English strings. As shown in the figure:

**Comment by luzhengang-phy** [comment]
![issue](https://user-images.githubusercontent.com/76544541/172396509-b8b19da2-7cc2-45fa-a62b-93cdf20cd92c.png)

**Comment by tillahoffmann** [comment]
Thanks for the screenshot. Could you please also share the input in text form?

**Comment by luzhengang-phy** [comment]
The screenshots show the printed English version of "I Love you" and the Chinese version of "我爱你". Results can be produced normally when printing English text, but not when printing Chinese.

**Comment by jiewangjs** [comment]
I would have wanted to file a same theme issue, and I found this one.
What I have experienced so far is that even including Chinese characters in the comment would also yield bug. 
![image](https://user-images.githubusercontent.com/11204422/174201443-0fcd4a03-67ec-4883-8d04-6386c4d58d2e.png)
But strangely enough, I do find peculiar instances that a few or a few line of chinese characters in the comment work.

**Comment by tillahoffmann** [comment]
Which python version are you using? Older versions sometimes have problems with unicode characters. I've tested the string you posted, and it seems to work ok for me (see below).

<img width="435" alt="image" src="https://user-images.githubusercontent.com/966348/174316938-bde429fc-92d0-4421-b831-074245c66224.png">

Here's the snippet to get the python version.

```python
import sys
print(sys.version)
```

**Comment by jiewangjs** [comment]
I am using 3.8.8 


|
|
|
|
|
---- Replied Message ----
| From | Till ***@***.***> |
| Date | 6/17/2022 22:21 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [tillahoffmann/obsidian-jupyter] The Chinese characters in the string are not supported (Issue #43) |

Which python version are you using? Older versions sometimes have problems with unicode characters. I've tested the string you posted, and it seems to work ok for me (see below).

Here's the snippet to get the python version.

importsysprint(sys.version)

**Comment by luzhengang-phy** [comment]
The version I used is shown here

| |
luzhengang0419
|
|
***@***.***
|
On 6/17/2022 22:21，Till ***@***.***> wrote：

Which python version are you using? Older versions sometimes have problems with unicode characters. I've tested the string you posted, and it seems to work ok for me (see below).

Here's the snippet to get the python version.

importsysprint(sys.version)

**Comment by tillahoffmann** [comment]
Hm, interesting. And which operating system are you on?

**Comment by jiewangjs** [comment]
I am on Windows 10. 




---- Replied Message ----
| From | Till ***@***.***> |
| Date | 6/17/2022 23:27 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [tillahoffmann/obsidian-jupyter] The Chinese characters in the string are not supported (Issue #43) |

Hm, interesting. And which operating system are you on?

**Comment by luzhengang-phy** [comment]
I am on Windows 10. 



| |
luzhengang0419
|
|
***@***.***
|
On 6/17/2022 23:27，Till ***@***.***> wrote：

Hm, interesting. And which operating system are you on?

**Comment by tillahoffmann** [comment]
My guess is that the encoding of Chinese characters fails on Windows. Unfortunately, I don't have a Windows machine to test on. Explicitly specifying an encoding might be able to resolve the issue if you want to give it a try. The relevant lines are 

https://github.com/tillahoffmann/obsidian-jupyter/blob/4b421d62a8d78793a3e399117c563a9a08f14b0d/main.ts#L111
https://github.com/tillahoffmann/obsidian-jupyter/blob/4b421d62a8d78793a3e399117c563a9a08f14b0d/obsidian-jupyter.py#L54-L60

**Comment by SpinnerGT** [comment]
I'm also having this issue, according to the author's solution, just need to add it in 
`response = json.dumps(response,ensure_ascii=False) `
In this way, the Chinese will not be garbled words, under win10
