### ISSUE TITLE
Why under live preview, only one code cell is supported ?

### ISSUE THREAD

**Issue by jiewangjs** [tillahoffmann/obsidian-jupyter#44]
Hi, greetings!
Not sure to call this an issue/bug, just as the title describes, when in live preview mode, different cells seem to be exactly isolated. Say: I import a library in the first cell, and run some inner method in the second cell, the second cell won't execute.
Can this be improved to be like the edit mode, aka, cells in the same file share one working jupyter kernel ?

Best regards !

**Comment by tillahoffmann** [comment]
This plugin currently uses the document id to decide whether to start a new kernel or reuse an existing one. It might be that document ids behave differently in live preview mode.

**Comment by jiewangjs** [comment]
Ok, I see. Would be better if it could be resolved, but I understand the difficulty.



| |
***@***.***
|
|
***@***.***
|




---- Replied Message ----
| From | Till ***@***.***> |
| Date | 08/24/2022 23:28 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [tillahoffmann/obsidian-jupyter] Why under live preview, only one code cell is supported ? (Issue #44) |

Reopened #44.
