### ISSUE TITLE
Feature Request: adopt output into md file

### ISSUE THREAD

**Issue by MartinKorz** [tillahoffmann/obsidian-jupyter#52]
Thanks for a great plugin!

In case that this is simple to do: Would it be possible to add the option to permanently add the currently shown cell output to the file?

At the moment, the cell output does not become part of the file, which I think is a good default behaviour. I can copy and paste the output into the file by hand to make it permanent. 
But as the output is already being rendered like a code block I was wondering whether it would be simple to e.g. add an "adopt output" button that makes it a part of the markdown file?

**Comment by ndahn** [comment]
I second this. Adding some form of mark or comment around the output (e.g. `%% jupyter-output %%`) would be required in order to update the output on subsequent runs. Or it could be another code block processor, since some outputs like rendered images likely have to be stored somewhere.

**Comment by MaartenSiersema** [comment]
I agree.. It would be good default behavior for reference or documentation to include code snippets which can reproduce the stored results.

**Comment by tillahoffmann** [comment]
I think the challenge here is that the output is HTML and the document is markdown. Storing the cached results elsewhere as mentioned by @ndahn is another option but likely requires a bit of work. Contributions welcome!

**Comment by ndahn** [comment]
Since #60 is was manually closed, does this mean there is some progress?

**Comment by faberf** [comment]
I am also interested in this feature.
