### ISSUE TITLE
setting tab missing

### ISSUE THREAD

**Issue by lumos0** [tillahoffmann/obsidian-jupyter#65]
**Describe the bug**
plugin setting tab is  missing 😂

don't know why 

re-install, tried .
restart obsidian,tried .

**Screenshots**
![image](https://user-images.githubusercontent.com/30490759/235194857-1096101d-0774-4e36-9eaa-310b6b28b4ca.png)
![image](https://user-images.githubusercontent.com/30490759/235194791-946f6d45-7ea3-4358-bb4e-2600c235c707.png)

**Comment by macnversion** [comment]
no  setting tab, too
