### ISSUE TITLE
Windows: error

### ISSUE THREAD

**Issue by ms3056** [tillahoffmann/obsidian-jupyter#8]
I am on Windows - Python is on my path, and I have set the path in the app settings all the way to the python.exe file. Is your app expecting a certain slash like // or \\ or / etc? 

I also had to copy manually the obsidian-jupyter.py file to my machine. 

**Describe the bug**
I am unable to run the test or other simple scripts. 

**Console output**
```
DevTools failed to load SourceMap: Could not parse content for app://obsidian.md/pickr.min.js.map: Unexpected end of JSON input
```

**Comment by tillahoffmann** [comment]
> I am on Windows - Python is on my path, and I have set the path in the app settings all the way to the python.exe file. Is your app expecting a certain slash like // or \ or / etc?

I'm afraid I don't have access to a windows machine so can't test in that environment. A path to the python interpreter that runs in the windows console *should* work.

> I am unable to run the test or other simple scripts.

Could you provide details on why you can't run the test? Is there no button or some other reason?

**Comment by ms3056** [comment]
I click the new test button in the plugin settings area and nothing happens - the result is the error message in the console I provided. 

Running the script in the preview mode (clicking RUN) the button changes to "RUNNING" but no result appears. 

I will continue to monitor - maybe someone else can get it working on Windows and be kind enough to post what they had to do. 

This is so cool - thanks for making it.

**Comment by ms3056** [comment]
The test function now passes. Running scripts still does not work - even:

`print('HI')`

or 

`print('HI')`
`pass`

**Comment by ms3056** [comment]
It is working - just needed to give it time to run - takes a while.

**Comment by tillahoffmann** [comment]
Yes, the first run can take a little while because the plugin needs to start up a python process, set up the kernel, etc.
