### ISSUE TITLE
Not finding Jupiter

### ISSUE THREAD

**Issue by swehba** [tillahoffmann/obsidian-jupyter#9]
**Describe the bug**
I have the plugin configured to find my Python binary. When I run a test from the plugin's config page, I see the following on the console:

```
created new client for doc test-document
main.ts:46 Traceback (most recent call last):
  File "/Users/swehba/Documents/Obsidian/swvault/.obsidian/plugins/obsidian-jupyter/obsidian-jupyter.py", line 3, in <module>
main.ts:46     from jupyter_client import KernelManager
ModuleNotFoundError: No module named 'jupyter_client'
```

The installation did not mention having to also install jupyter — but clearly, that is also required.

So, my question is, how do I specify to the plugin where jupyter is installed? Does it have to be installed in the same location as the Python binary? Should there be a configuration setting for jupyter too?

Here is the markdown code in edit mode: https://cln.sh/gMv6Ra+

Here is what I see in preview mode: https://cln.sh/8pVkhM+

Notice that in preview mode I don't see a "Run" button because another plugin is showing a "Copy" button. Is this another problem?

**Screenshots**
See above.

**Console output**
See above.

**Comment by tillahoffmann** [comment]
I've added installation instructions [here](https://github.com/tillahoffmann/obsidian-jupyter#installation).

> Notice that in preview mode I don't see a "Run" button because another plugin is showing a "Copy" button. Is this another problem?

Yes, that's likely a conflict that's difficult to resolve without coordinating between different plugin developers. Which plugin is showing the `Copy` button?

**Comment by swehba** [comment]
The plug in is "Copy button for code blocks". However, there is a much better plugin -- "Code Block Enhancer". It adds line numbers, and only shows the copy button on hover. So, I'll just switch to it.

I might be a nice enhancement to add an option of choosing which corner to display the "Run Jupiter" button (or whatever it's called once I get it working ;-).

Anyway, thanks for responding, and thanks for a very significant plugin.

**Comment by swehba** [comment]
Just to follow up, everything is now working nicely. I am able to use "Code Block Enhancer", but its Copy button seems to be obscured by the Jupyter plugin. Not a big deal. Here's a screenshot: https://cln.sh/ifLJJ4+
